### ISSUE TITLE
Is this repo usable ? 

### ISSUE THREAD

**Issue by apirrone** [rgalljamov/DRLoco#1]
Hello ! 

Is this project still usable ? The Installation.md file refers to files that do not exist, and there is no setup.cfg or setup.py to install the package so that the installation instructions here https://drloco.readthedocs.io/en/latest/main/install.html work. 

Thanks !

**Comment by rgalljamov** [comment]
Hi @apirrone, 

Thanks for your interest in the repository and for reaching out!

I haven't looked into this repository for about three years. However, I know that a former colleague used it multiple years after it was generated, and I still see some activities from people forking it. So, I would expect that it’s still usable.

This project is not intended to be installed as a package. It is designed as a framework that you can use to train your own RL agents following the DeepMimic approach. You should fork the repository and then use it according to the provided documentation.

You might need to install more recent versions of dependencies or make minor adjustments. Please feel free to fork it and try it out. I think it should work, and you might need to make some adjustments.

Best regards and wishes, 
Rustam
